apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-provisioner
  namespace: kube-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-provisioner
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      serviceAccountName: efs-provisioner
      containers:
      - name: efs-provisioner
        image: amazon/aws-efs-csi-driver:v2.0.3
        args:
        - "--provisioner=efs.csi.aws.com"
        - "--volume-driver=efs.csi.aws.com"
        ports:
        - containerPort: 9808
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: efs-provisioner
  namespace: kube-system
spec:
  ports:
    - port: 9808
      targetPort: metrics
  selector:
    app: efs-provisioner
